name: cd

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout go
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5

      - name: Build notely
        run: scripts/buildprod.sh
      
